[build]
target = "riscv32imafc-unknown-none-elf"

[target.riscv32imafc-unknown-none-elf]
runner = "wlink flash --enable-sdi-print --watch-serial"
# runner = "wlink -v flash --no-erase --dry-run"
# runner = "probe-rs run --chip CH32V307 --probe 1a86:8010 --connect-under-reset"
# runner = "wlink -v flash"

# Use the following or build.rs
#rustflags = [
#  "-C", "link-arg=-Tlink.x",
#]
# .cargo/config.toml
[env]
DEFMT_LOG = "trace"
